[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Urlaubsliste"
version = "1.3.1"
authors = [{ name = "Dominik Reinartz", email = "dominik.reinartz@proton.me" }]
description = "Program zum Verwalten hierarchischer Listen."
readme = "README.md"
requires-python = ">=3.9"
keywords = ["listenverwaltung", "gui"]
license = { text = "GPLv3" }
dependencies = [
    "PyQt6>=6.9.1",
    "reportlab>=4.4.3",
    "pyqt-utils @ git+https://github.com/TheCheese42/pyqt-utils.git",
]

[project.optional-dependencies]
dev = ["nuitka>=2.7.12", "isort>=6.0.1", "flake8>=7.3.0"]

[project.scripts]
urlaubsliste = "urlaubsliste.__main__:main"
