name: Build Urlaubsliste using Nuitka (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/*requirements.txt

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y pyqt5-dev-tools qtchooser qttools5-dev-tools
          sudo apt install -y patchelf ccache
          pip install -r requirements.txt -r dev-requirements.txt
      
      - name: Compile Resources
        run: |
          pyqt-utils urlaubsliste --compile-ui --compile-icons

      - name: Build Executable
        run: |
          chmod +x ./build-linux.sh
          ./build-linux.sh

      - name: Finish Artifact Files
        run: |
          mv build/urlaubsliste.bin urlaubsliste-linux-x86_64.bin

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            urlaubsliste-linux-x86_64.bin
          include-hidden-files: true
